# Generated by Django 4.2.3 on 2023-07-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nofication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('info', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
