# Generated by Django 4.2.3 on 2023-07-30 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_nofication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nofication',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='nofication',
            name='date',
        ),
        migrations.RemoveField(
            model_name='nofication',
            name='paid',
        ),
    ]
