# Generated by Django 4.2.3 on 2023-07-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notification_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='pub_date',
        ),
    ]
