# Generated by Django 4.2.3 on 2023-07-31 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_date_notification_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='value',
            new_name='point',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='link',
            new_name='prompt',
        ),
    ]
