# Generated by Django 4.2.3 on 2023-07-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='yttasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.yttasker'),
        ),
    ]
